# Generated by Django 3.2.16 on 2022-11-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='postcode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
